### ISSUE TITLE
这并不是Issues

### ISSUE THREAD

**Issue by Nstd** [HurryYU/BestActivityResult#1]
库主的这个想法不错！先赞一波。👍 

受库主启发，还有一些变形做法，可以在自己的BaseActivity或者BaseFragment实现统一的接口，然后用自增的requestCode关联回调的方式去做。

总之库主的这个想法很棒~

**Comment by HurryYU** [comment]
> 库主的这个想法不错！先赞一波。👍
> 
> 受库主启发，还有一些变形做法，可以在自己的BaseActivity或BaseFragment实现统一的接口，然后用自增的请求代码关联的方式去做。
> 
> 总之库主的这个想法很棒〜

感谢您的支持~
